# Generated by Django 6.0.2 on 2026-03-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_activitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="core.task",
            ),
        ),
    ]
