# Generated by Django 6.0.2 on 2026-03-04 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_customuser_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="assigned_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
