# Generated by Django 6.0.2 on 2026-03-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_invite_assigned_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_manager_type",
            field=models.BooleanField(default=False),
        ),
    ]
