# Generated by Django 6.0.2 on 2026-03-05 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_customuser_dob_customuser_employee_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="sop_file",
        ),
        migrations.RemoveField(
            model_name="project",
            name="sop_link",
        ),
        migrations.AddField(
            model_name="invite",
            name="contract_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="emp_id_counter",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="employee_id",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name="SOPDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sop_file", models.FileField(blank=True, null=True, upload_to="sop/")),
                ("sop_link", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sop_documents",
                        to="core.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_sops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
