# Generated by Django 6.0.2 on 2026-03-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_invite_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
