# Generated by Django 6.0.2 on 2026-03-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_task_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="task_number_counter",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="task_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
