# Generated by Django 6.0.2 on 2026-03-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_project_task_number_counter_task_task_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="moved_to_blocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="moved_to_inprogress_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="moved_to_todo_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
