# Generated by Django 6.0.2 on 2026-03-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_task_moved_to_blocked_at_task_moved_to_inprogress_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
