# Generated by Django 6.0.2 on 2026-03-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="task_only",
            field=models.BooleanField(default=False),
        ),
    ]
